server:
  port: 8001

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/livestream?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "wnstjr4231!"

  cloud:
    discovery:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: "sad98fjsd98fj8zmvusrvduawrevuyawr0vayvwrvawr=vwaa=yrav"

logging:
  level:
    com.authservice: debug # ? ??? debug
