server:
  port: 80

spring:
  application:
    name: live_stream

  thymeleaf:
    cache: false

  datasource:
    url: jdbc:postgresql://localhost:5432/livestream
    driver-class-name: org.postgresql.Driver
    username: livestream
    password: "sj102030"

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true


jwt:
  secret: "sad98fjsd98fj8zmvusrvduawrevuyawr0vayvwrvawr=vwaa=yrav"