server:
  port: 80

spring:
  application:
    name: live_stream

  thymeleaf:
    cache: false

  datasource:
    url: jdbc:mysql://localhost:3306/livestream?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "wnstjr4231!"

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: "sad98fjsd98fj8zmvusrvduawrevuyawr0vayvwrvawr=vwaa=yrav"

logging:
  level:
    com.live_stream: debug # 내 코드만 debug
