server:
  port: 8003

spring:
  application:
    name: camera-service

#db 로컬호스트 주의
  datasource:
    url: jdbc:mysql://mysql:3306/livestream?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "wnstjr4231!"

  cloud:
    discovery:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  level:
    com.rts.cameraservice: debug
